'use client';

import { Download, Maximize2, X } from 'lucide-react';
import { useState, useCallback } from 'react';

interface ImageGridProps {
  images: string[];
  provider: string;
  isLoading: boolean;
  cached?: boolean;
}

export default function ImageGrid({
  images,
  provider,
  isLoading,
  cached,
}: ImageGridProps) {
  const [fullscreenImage, setFullscreenImage] = useState<string | null>(null);

  const handleDownload = useCallback((base64: string, index: number) => {
    const timestamp = performance.now().toString(36);
    const link = document.createElement('a');
    link.href = `data:image/png;base64,${base64}`;
    link.download = `micro-banana-${timestamp}-${index + 1}.png`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  }, []);

  if (isLoading) {
    return (
      <div className="w-full max-w-3xl mx-auto mt-8">
        <div className="grid grid-cols-2 gap-3">
          {[...Array(4)].map((_, i) => (
            <div
              key={i}
              className="aspect-square rounded-xl bg-white/[0.05] border border-white/10 animate-pulse flex items-center justify-center"
            >
              <div className="flex flex-col items-center gap-3">
                <div className="h-8 w-8 animate-spin rounded-full border-2 border-white/10 border-t-yellow-400" />
                <span className="text-xs text-white/30">Generating...</span>
              </div>
            </div>
          ))}
        </div>
        <div className="mt-4 flex items-center justify-center gap-2">
          <div className="h-1.5 w-1.5 rounded-full bg-yellow-400 animate-bounce" />
          <div className="h-1.5 w-1.5 rounded-full bg-yellow-400 animate-bounce [animation-delay:0.2s]" />
          <div className="h-1.5 w-1.5 rounded-full bg-yellow-400 animate-bounce [animation-delay:0.4s]" />
          <span className="ml-2 text-sm text-white/40">
            AI is creating your images...
          </span>
        </div>
      </div>
    );
  }

  if (images.length === 0) return null;

  return (
    <>
      <div className="w-full max-w-3xl mx-auto mt-8">
        {/* Provider badge */}
        <div className="mb-3 flex items-center justify-between">
          <div className="flex items-center gap-2">
            <div className="h-2 w-2 rounded-full bg-green-400" />
            <span className="text-xs text-white/50">
              Generated by{' '}
              <span className="text-yellow-400 font-medium">{provider}</span>
            </span>
            {cached && (
              <span className="rounded-full bg-blue-500/20 px-2 py-0.5 text-[10px] text-blue-400">
                cached
              </span>
            )}
          </div>
          <span className="text-xs text-white/30">
            {images.length} image{images.length !== 1 ? 's' : ''}
          </span>
        </div>

        {/* Image grid */}
        <div className="grid grid-cols-2 gap-3">
          {images.map((img, i) => (
            <div
              key={i}
              className="group relative aspect-square overflow-hidden rounded-xl border border-white/10 bg-white/[0.03] transition-all hover:border-white/20"
            >
              <img
                src={`data:image/png;base64,${img}`}
                alt={`Generated image ${i + 1}`}
                className="h-full w-full object-cover"
              />
              {/* Overlay on hover */}
              <div className="absolute inset-0 flex items-end justify-between bg-gradient-to-t from-black/60 via-transparent to-transparent p-3 opacity-0 transition-opacity group-hover:opacity-100">
                <span className="text-xs text-white/70">#{i + 1}</span>
                <div className="flex gap-2">
                  <button
                    onClick={() => setFullscreenImage(img)}
                    className="flex h-8 w-8 items-center justify-center rounded-lg bg-white/20 text-white backdrop-blur-sm hover:bg-white/30 transition-colors"
                  >
                    <Maximize2 className="h-4 w-4" />
                  </button>
                  <button
                    onClick={() => handleDownload(img, i)}
                    className="flex h-8 w-8 items-center justify-center rounded-lg bg-white/20 text-white backdrop-blur-sm hover:bg-white/30 transition-colors"
                  >
                    <Download className="h-4 w-4" />
                  </button>
                </div>
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* Fullscreen modal */}
      {fullscreenImage && (
        <div
          className="fixed inset-0 z-[100] flex items-center justify-center bg-black/90 backdrop-blur-sm p-4"
          onClick={() => setFullscreenImage(null)}
        >
          <button
            onClick={() => setFullscreenImage(null)}
            className="absolute top-4 right-4 flex h-10 w-10 items-center justify-center rounded-full bg-white/10 text-white hover:bg-white/20 transition-colors"
          >
            <X className="h-5 w-5" />
          </button>
          <img
            src={`data:image/png;base64,${fullscreenImage}`}
            alt="Fullscreen"
            className="max-h-[90vh] max-w-[90vw] rounded-lg object-contain"
            onClick={(e) => e.stopPropagation()}
          />
        </div>
      )}
    </>
  );
}
